### ISSUE TITLE
Wrong Language in Frontend

### ISSUE THREAD

**Issue by Hobokens** [Gregor-Agnes/newsletter_subscribe#78]
Hi @Gregor-Agnes ,

I have a strange issue in frontend (TYPO3 11.5.20,  newsletter_subscribe 5.0.0). In my two language page German is default language:

```
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-de
    direction: ltr
    flag: de

  -
    title: English
    enabled: true
    languageId: 1
    base: /
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: en-us-gb
```
In your extension all texts in frontend are in English and the Mails and the labels in backend are in German. I expect German for the frontend if I have chosen German.
